export const SET_ERROR = 'SET_ERROR'
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS'
export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER'
export const SET_ITEMS = 'SET_ITEMS'
export const ADD_ITEMS = 'ADD_ITEMS'
export const DELETE_ITEM = 'DELETE_ITEM'